---
# tasks file for docker_node
- include_role:
    name: "{{ roleinputvar }}"
  loop:
    - farynam.mfitbs_disable_ipv6
  loop_control:
    loop_var: roleinputvar

- name: change apt perms
  file:
    path: /etc/apt/trusted.gpg
    owner: _apt
  ignore_errors: yes

- name: Install requirements
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - gnupg2

- name: Import certs
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Check whether /etc/apt/sources.list contains docker repo
  command: grep -Fq "https://download.docker.com/linux/debian" /etc/apt/sources.list
  register: dockerInRepo
  check_mode: no
  ignore_errors: yes

- name: Add repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  when: dockerInRepo.rc

- name: update
  apt:
    update_cache: yes

- name: Install docker
  apt:
    name: docker-ce=5:19.03.2~3-0~debian-stretch

- name: Disable unwanted services
  systemd:
    enabled: false
    state: stopped
    name: "{{ service }}"
  ignore_errors: yes
  loop:
    - exim4
    - avahi-daemon
  loop_control:
    loop_var: service

- name: Give node a meaningful name
  shell: echo "{{ inventory_hostname }}" > /etc/hostname

- name: Install iptables-persistent
  apt:
    name: iptables-persistent

- name: Template iptables
  template:
    src: templates/iptables.tpl
    dest: /etc/iptables/rules-1.out
    mode: '0760'

- name: Run new rules
  command: /etc/iptables/rules-1.out
  register: rules_run

- name: Save iptables rules
  shell: "/sbin/iptables-save > /etc/iptables/rules.v4"
  when: rules_run.rc == 0
