- name: Import debian 9 related tasks
  import_tasks: debian9.yml
  when: >
    ansible_distribution == OS_SUPORTED_DIST
    and ansible_distribution_release == OS_SUPORTED_REL

- name: Check if OS compatibility
  import_tasks: other.yml
  when: >
    ansible_distribution != OS_SUPORTED_DIST
    and ansible_distribution_release != OS_SUPORTED_REL