---
# tasks file for docker_node
- include_role:
    name: "{{ roleinputvar }}"
  loop:
    - farynam.mfitbs_disable_ipv6
  loop_control:
    loop_var: roleinputvar

- name: change apt perms
  file:
    path: /etc/apt/trusted.gpg
    owner: _apt

- name: Install requirements
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - gnupg2

- name: Import certs
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Check whether /etc/apt/sources.list contains docker repo
  command: grep -Fq "https://download.docker.com/linux/debian" /etc/apt/sources.list
  register: dockerInRepo
  check_mode: no
  ignore_errors: yes

- name: Add repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  when: not dockerInRepo

- name: update
  apt:
    update_cache: yes

- name: Install docker
  apt:
    name: docker-ce=5:19.03.2~3-0~debian-stretch

- name: Disable unwanted services
  systemd:
    enabled: false
    state: stopped
    name: "{{ service }}"
  loop:
    - exim4
    - avahi-daemon
  loop_control:
    loop_var: service

- name: Give node a meaningful name
  shell: echo "{{ inventory_hostname }}" > /etc/hostname

- name: Install iptables-persistent
  apt:
    name: iptables-persistent

- name: Save old iptables
  command: cp /etc/iptables/rules.out /etc/iptables/rules_old.out
  args:
    removes: /etc/iptables/rules.out

- name: Template iptables
  template:
    src: templates/iptables.tpl
    dest: /etc/iptables/rules.out
    mode: '0760'

- name: Grab new rules
  stat:
    path: /etc/iptables/rules.out
  register: newRules

- name: Grab old rules
  stat:
    path: /etc/iptables/rules_old.out
  register: oldRules

- name: Run new rules
  command: /etc/iptables/rules.out
  when: oldRules.stat.checksum is undefined or newRules.stat.checksum != oldRules.stat.checksum

- name: Save iptables rules
  shell: "/sbin/iptables-save > /etc/iptables/rules.v4"
  when: oldRules.stat.checksum is undefined or newRules.stat.checksum != oldRules.stat.checksum
